### ISSUE TITLE
Build and release failed to release YT

### ISSUE THREAD

**Issue by Fred-Vatin** [nikhilbadyal/docker-py-revanced#580] opened 2024-11-18 00:09 UTC
### Request guidelines

- [X] I've read the [issue guidelines](https://github.com/nikhilbadyal/docker-py-revanced#only-builder-support)

### Name

Youtube

### Error log or link to the logs if using Github Action

Action `Build & release` only releases microG and ignore `PATCH_APPS` : [log](https://github.com/Fred-Vatin/docker-py-revanced/actions/runs/11883275382/job/33109787969). Line 201 reports error but the job itself is green.

![image](https://github.com/user-attachments/assets/0a98acdb-51bf-4e62-8b98-7eb770f57eb6)

### ENVS

```Dotenv
#Global:
PERSONAL_ACCESS_TOKEN=***
EXTRA_FILES=https://github.com/ReVanced/GmsCore/releases/latest@Revanced-Microg.apk
PATCH_APPS=youtube,youtube_music
GLOBAL_CLI_DL=https://github.com/revanced/revanced-cli
GLOBAL_PATCHES_DL=https://github.com/revanced/revanced-patches
GLOBAL_PATCHES_JSON_DL=https://api.revanced.app/v4/patches/list

#YouTube:
YOUTUBE_CLI_DL=https://github.com/inotia00/revanced-cli
YOUTUBE_PATCHES_DL=https://github.com/YT-Advanced/ReX-patches
YOUTUBE_PATCHES_JSON_DL=https://github.com/YT-Advanced/ReX-patches
YOUTUBE_EXCLUDE_PATCH=custom-branding-icon-revancify-blue,custom-branding-icon-revancify-red,custom-branding-icon-mmt,custom-branding-youtube-name,enable-debug-logging

#YouTube Music:
YOUTUBE_MUSIC_CLI_DL=https://github.com/inotia00/revanced-cli
YOUTUBE_MUSIC_PATCHES_DL=https://github.com/YT-Advanced/ReX-patches
YOUTUBE_MUSIC_PATCHES_JSON_DL=https://github.com/YT-Advanced/ReX-patches
YOUTUBE_MUSIC_EXCLUDE_PATCH=custom-branding-icon-mmt,custom-branding-icon-revancify-blue,custom-branding-icon-revancify-red,custom-branding-music-name,enable-compact-dialog,enable-debug-logging
```

### Additional info

Subsidiary question: although I don’t use upload to telegram and so, the `auto build & release` action is triggered and when it fails (almost every time in the past for me), it deletes the previous valid release from github because `GitHub Cleanup` is called on any case. How to prevent failure from cleaning up previous builds? I’d like to keep the last two releases in case the last one is buggy.

**Comment by nikhilbadyal** [comment] 2024-11-18 16:07
It's happening because [Yt-Advanced ](https://github.com/revanced/revanced-patches) patches are not updated and doesn't follow the v5. Also duplicate of #581 . 


You can monitor the progress there. 

For Subsidiary question - The Builder is currently setup in a way that it cleans up all the older builds. If you have any specific requirement. You can open a new feature request ticket.

**Closed by nikhilbadyal** 2024-11-18 16:07 UTC
Labels: bug🐞
