### ISSUE TITLE
The new YouTube Revanced version 17.36.37 crash when a video is played

### ISSUE THREAD

**Issue by yoloyol69** [nikhilbadyal/docker-py-revanced#15] opened 2022-09-28 14:00 UTC
The newest release of YT crashes. I have confirmed it with few other people that they also facing the same issue. All of us have microG installed, we clear app data and cache, reinstall the apps but still crashing.
https://github.com/nikhilbadyal/docker-py-revanced/releases/tag/Build-2022.09.27-21.51.13

**Comment by nikhilbadyal** [comment] 2022-09-28 16:53
Might have been the revanced issue. I dont do anything special other than building as they recommended. Anyway, I triggered a rebuild and installed it on my device and its working fine for me. Can you retry  [from here](https://github.com/nikhilbadyal/docker-py-revanced/releases/download/Build-2022.09.28-22.17.03/Re-youtube-17-36-37-output.apk)

**Comment by nikhilbadyal** [comment] 2022-09-30 14:08
Closing as unable to reproduce the issue. Please open a new issue if you face a similar issue again.

**Closed by nikhilbadyal** 2022-09-30 14:08 UTC
